src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $Price = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

templates/bezoeker/addtasks.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container-sm px-5">
        {{ form(form) }}
    </div>
{% endblock %}

templates/bezoeker/mynumber.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div>
        <html><body><h1 style="text-align: center;">My Lucky number: {{ number }}</h1></body></html>
        <a href="{{ path('lucky_number') }}">go To random number</a>
    </div>
{% endblock %}

templates/bezoeker/number.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div>
    <html><body><h1 style="text-align: center;">Lucky number: {{ number }}</h1></body></html>
    {% for game in games %}
        <h4>{{ game }}</h4>
    {% endfor %}
</div>
{% endblock %}

templates/bezoeker/productsShow.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div style="margin: auto;">
        <table style="border-style: solid; border-color: black; margin: auto;">
            <tr><th style="border-style: solid; border-color: black; border-width: 2px;"><h4>ID</h4></th>
                <th style="border-style: solid; border-color: black; border-width: 2px;"><h4>Name</h4></th>
                <th style="border-style: solid; border-color: black; border-width: 2px;"><h4>Price</h4></th>
                <th style="border-style: solid; border-color: black; border-width: 2px;"><h4>Category</h4></th></tr>
            {% for product in products %}
                <tr><td style="border-style: solid; border-color: black; border-width: 2px;"><h4>{{ product.id }}</h4></td>
                    <td style="border-style: solid; border-color: black; border-width: 2px;"><h4>{{ product.name }}</h4></td>
                    <td style="border-style: solid; border-color: black; border-width: 2px;"><h4>{{ product.price }}</h4></td>
                    <td style="border-style: solid; border-color: black; border-width: 2px;"><h4>{{ product.category.name }}</h4></td></tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}